name: Dependabot auto-merge
on: pull_request_target
permissions:
  pull-requests: write
  content: write
jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dev Dependencies
        if: ${{ steps.dependabot-metadata.outputs.dependency-type == 'direct:development' }}
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          pull-request-number: ${{github.event.pull_request.number}}
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: merge
      - name: Enable auto-merge for Indirect Dependencies
        if: ${{ steps.dependabot-metadata.outputs.dependency-type == 'indirect:production' }}
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          pull-request-number: ${{github.event.pull_request.number}}
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: merge
      - name: Enable auto-merge for Minor Production Updates
        if: ${{steps.dependabot-metadata.outputs.dependency-type == 'direct:production' && (steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor' || steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch')}}
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          pull-request-number: ${{github.event.pull_request.number}}
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: merge
